global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # ============================================================
  # OpenTelemetry Collector
  # ============================================================
  - job_name: "otel-collector"
    static_configs:
      - targets:
          - "otel-collector:8889"


  # ============================================================
  # Fedora Host
  # ============================================================
  - job_name: "node-exporter"
    static_configs:
      - targets:
          - "node-exporter:9100"


  # ============================================================
  # Docker Containers
  # ============================================================
  - job_name: "cadvisor"
    static_configs:
      - targets:
          - "cadvisor:8080"


  # ============================================================
  # Prometheus itself
  # ============================================================
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "prometheus:9090"