apiVersion: 1

datasources:

  # ============================================================
  # PROMETHEUS
  # ============================================================

  - name: Prometheus

    type: prometheus

    access: proxy

    url: http://prometheus:9090

    isDefault: true

    editable: false


  # ============================================================
  # LOKI
  # ============================================================

  - name: Loki

    type: loki

    access: proxy

    url: http://loki:3100

    editable: false


  # ============================================================
  # TEMPO
  # ============================================================

  - name: Tempo

    type: tempo

    access: proxy

    url: http://tempo:3200

    editable: false

    jsonData:

      tracesToLogsV2:

        datasourceUid: loki

        spanStartTimeShift: "-5m"

        spanEndTimeShift: "5m"

        tags:
          - service.name
          - deployment.environment


      tracesToMetrics:

        datasourceUid: prometheus

        tags:
          - service.name
          - job


      serviceMap:

        datasourceUid: prometheus